/**
 * Peatio SDK
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.4
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TickerInfoTicker'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TickerInfoTicker'));
  } else {
    // Browser globals (root is window)
    if (!root.PeatioSdk) {
      root.PeatioSdk = {};
    }
    root.PeatioSdk.TickerInfo = factory(root.PeatioSdk.ApiClient, root.PeatioSdk.TickerInfoTicker);
  }
}(this, function(ApiClient, TickerInfoTicker) {
  'use strict';




  /**
   * The TickerInfo model module.
   * @module model/TickerInfo
   * @version 0.2.4
   */

  /**
   * Constructs a new <code>TickerInfo</code>.
   * @alias module:model/TickerInfo
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TickerInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TickerInfo} obj Optional instance to populate.
   * @return {module:model/TickerInfo} The populated <code>TickerInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('at')) {
        obj['at'] = ApiClient.convertToType(data['at'], 'Number');
      }
      if (data.hasOwnProperty('ticker')) {
        obj['ticker'] = TickerInfoTicker.constructFromObject(data['ticker']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} at
   */
  exports.prototype['at'] = undefined;
  /**
   * @member {module:model/TickerInfoTicker} ticker
   */
  exports.prototype['ticker'] = undefined;



  return exports;
}));


